use std::path::{Path, PathBuf};

pub fn run(harness: Option<&str>, all: bool) {
    let local_base = std::env::current_dir().unwrap_or_default().join(".heald");
    let global_base = dirs::home_dir().unwrap_or_default().join(".heald");

    let mut rules_docs = load_all_docs(&global_base.join("rules"));
    rules_docs.extend(load_all_docs(&local_base.join("rules")));

    let mut skills_docs = load_all_docs(&global_base.join("skills"));
    skills_docs.extend(load_all_docs(&local_base.join("skills")));

    // Build a dynamic routing table with ABSOLUTE paths to global skills.
    let global_skills_dir = global_base.join("skills");
    let routing_table = build_routing_table(&skills_docs, &global_skills_dir);

    // Always regenerate the global ~/.heald/AGENTS.md — the one canonical reference
    // that every AI agent's global config points at.
    sync_global_agents_md(&global_base, &rules_docs, &skills_docs, &routing_table);

    // Locally: just write one AGENTS.md in the project root.
    // No CLAUDE.md, no .cursor/ scatter, no .hermes/ — those are handled globally by init.
    if all || harness.is_none() {
        sync_local_agents_md(&rules_docs, &routing_table);
    } else if let Some(h) = harness {
        match h {
            "agents" | "agents_md" => sync_local_agents_md(&rules_docs, &routing_table),
            other => println!("Unknown harness: {}. Local sync only writes AGENTS.md.", other),
        }
    }
    crate::cmd::map::run();
}

/// Load all OKF documents from a directory, skipping broken files silently.
fn load_all_docs(dir: &Path) -> Vec<crate::okf::Document> {
    let mut docs = Vec::new();
    if !dir.exists() {
        return docs;
    }
    let walker = walkdir::WalkDir::new(dir).into_iter().filter_map(|e| e.ok());
    for entry in walker {
        let path = entry.path();
        if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("md") {
            if let Ok(doc) = crate::okf::Document::from_file(path) {
                docs.push(doc);
            }
        }
    }
    docs
}

/// Build a markdown routing table from whatever skills exist.
/// Paths are ABSOLUTE pointing to ~/.heald/skills/ so agents can load them
/// from any project directory without the skill files needing to be local.
fn build_routing_table(skills: &[crate::okf::Document], global_skills_dir: &Path) -> String {
    if skills.is_empty() {
        return String::new();
    }

    let mut table = String::from(
        "\n## Skill Routing Table\n\
         Load the relevant skill file before starting any task that matches the trigger.\n\n\
         | When working on...                     | Load this skill file             |\n\
         | -------------------------------------- | -------------------------------- |\n"
    );

    for skill in skills {
        let title = skill.frontmatter.effective_title();
        let slug = title.to_lowercase().replace(' ', "-");

        // Absolute path so agents can read it from any working directory.
        let abs_path = global_skills_dir.join(format!("{}.md", slug));
        let path_str = abs_path.to_str().unwrap_or("").replace('\\', "/");

        // Use triggers if declared; fall back to description, then title.
        let trigger_text = if let Some(triggers) = &skill.frontmatter.triggers {
            triggers.join(", ")
        } else if let Some(desc) = &skill.frontmatter.description {
            desc.clone()
        } else {
            title.to_string()
        };

        table.push_str(&format!(
            "| {:<38} | `{}` |\n",
            trigger_text, path_str
        ));
    }

    table
}

/// Universal Heald instructions injected into every compiled file.
fn heald_instructions() -> String {
    String::from(
        "\n\n## CRITICAL HEALD INSTRUCTIONS\n\
         You MUST run `heald context agents` ONCE as your very first tool call in a new session/conversation to load project context.\n\
         You MUST run `heald remember --type decision --title '...' --body '...'` to log major architectural or design decisions when you make them.\n\
         You CAN run `heald forget <slug-or-title>` to remove a memory document if it becomes outdated or incorrect.
         You CAN run `heald map` to see a fast repository map and cross-references.
         You CAN run `heald blame <path>` to see which memory decisions touched a given file.
         You MUST run `heald finalize --summary '...'` as your very last tool call before finishing the session.\n"
    )
}

const HEADER: &str =
    "<!-- Generated by heald sync — do not edit directly. Edit .heald/rules/ instead. -->\n\n";

/// Write the global ~/.heald/AGENTS.md — the canonical universal reference.
/// This is what you point Claude Code, Codex, and any other agent at.
fn sync_global_agents_md(
    global_base: &Path,
    rules: &[crate::okf::Document],
    skills: &[crate::okf::Document],
    routing_table: &str,
) {
    let out_path = global_base.join("AGENTS.md");
    let mut content = String::new();
    content.push_str(HEADER);
    content.push_str("# Heald — Universal Agent Context\n\n");
    content.push_str(
        "Heald is your project memory and rules store. It keeps all AI coding agents \
         aligned to the same decisions, rules, and skills regardless of which harness you use.\n\n"
    );

    // Rules section
    if !rules.is_empty() {
        content.push_str("## Project Rules\n\n");
        for rule in rules {
            if let Some(title) = &rule.frontmatter.title {
                content.push_str(&format!("### {}\n\n{}\n\n", title, rule.content));
            } else {
                content.push_str(&format!("{}\n\n", rule.content));
            }
        }
    }

    // Dynamic routing table
    if !skills.is_empty() {
        content.push_str(routing_table);
        content.push('\n');
    }

    content.push_str(&heald_instructions());
    safe_write(&out_path, &content);
}

/// Write one AGENTS.md into the local project root.
/// That's the only local file heald writes — clean and simple.
fn sync_local_agents_md(rules: &[crate::okf::Document], routing_table: &str) {
    let out_path = PathBuf::from("AGENTS.md");
    let extra = format!("{}{}", routing_table, heald_instructions());
    write_rules_file(&out_path, rules, &extra);
}


fn write_rules_file(path: &Path, rules: &[crate::okf::Document], extra: &str) {
    let mut content = String::new();
    content.push_str(HEADER);
    for rule in rules {
        if let Some(title) = &rule.frontmatter.title {
            content.push_str(&format!("# {}\n\n{}\n\n", title, rule.content));
        } else {
            content.push_str(&format!("{}\n\n", rule.content));
        }
    }
    content.push_str(extra);
    safe_write(path, &content);
}

fn safe_write(path: &Path, content: &str) {
    if path.exists() {
        let existing = std::fs::read_to_string(path).unwrap_or_default();
        if !existing.starts_with("<!-- Generated by heald sync") {
            println!(
                "WARNING: {} has manual edits — skipping overwrite. Delete it to regenerate.",
                path.display()
            );
            return;
        }
    }
    std::fs::write(path, content).unwrap();
    println!("Compiled to {}", path.display());
}
